GRANT CREATE VIEW TO SCOTT;

--CDB로 바꿔야한다.
ALTER SESSION SET CONTAINER =XEPDB1


SELECT * FROM SYSTEM_PRIVILEGE_MAP;
SELECT * FROM TABLE_PRIVILEGE_MAP;

ALTER USER SCOTT ACCOUNT UNLOCK
--ALTER USER USER IDENTIFIED BY PASSWORD


ALTER SESSION SET CONTAINER=XEPDB1;
GRANT EXECUTE ON SCOTT.TO_ASTERISK TO HR; //다른 계정에 권한 부여하기